# SEO site settings
title: "Eric Mascot"
description: "Tutorials and stuff from a physics grad student"
url: "http://www.ericmascot.com"
author: "Eric Mascot"
logo: "img/logo.png"

# Site settings
baseurl: ""
image: "img/home-bg.jpg"
copyright_name: "Eric Mascot"
github_username: emascot
email_username: emasco2@uic.edu
# twitter_username:
# facebook_username:

# Google Analytics
google_tracking_id: UA-82758576-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
  - "assets/**/*"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "CNAME"
  - "*.sublime-*"
  - "Gemfile"
  - "Gemfile.lock"

gems:
  - "jekyll-paginate"
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"
